### ISSUE TITLE
What happens to multi-object templates?

### ISSUE THREAD

**Issue by artisticcheese** [happytal/substitute-variables#5]
Hello,

What would happen with file like below
```
apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  selector:
    app: esb-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esb-api
  namespace: dev
```
